### PR TITLE
Feature/bsa profile

### PR DESCRIPTION
**Pull request by Thierrymanuel11**
First update of the profile files.

### CODE REVIEW

**Review by jarviscanada — CHANGES_REQUESTED** [review]
Change from BSA profile template to regular dev template

**Comment by Thierrymanuel11** [comment]
It seems like all the README and yaml files are the same as the normal template I had to respect about that so I don't exactly remember how I did that part by I think it is all good.

**Comment by Thierrymanuel11** [comment]
Already change the README file

**Comment by Thierrymanuel11** [comment]
Profile updated

**Comment by Thierrymanuel11** [comment]
Profile updated

**Pull request merged**
